yolo_model:

  config_file:
    name: yolov2-tiny.cfg
  weight_file:
    name: yolov2-tiny.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - car
      - motorbike
      - truck

# Needs retrained model to work with only these labels.